apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hackssh.fullname" . }}-private
  labels:
    {{ include "hackssh.labels" . | indent 4 | trim }}
data:
  hackssh_host_rsa_key: |-
    {{ .Values.host.keys | b64enc }}
