apiVersion: v1
kind: Service
metadata:
  name: {{ include "hackssh.fullname" . }}
  labels:
    {{ include "hackssh.labels" . | indent 4 | trim }}
{{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | indent 4 | trim }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ssh
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.extport }}
      protocol: TCP
  selector:
    {{ include "hackssh.selector" . | indent 4 | trim }}
